#version 460

layout (local_size_x = 16, local_size_y = 16) in;

layout (rgba16f, set = 0, binding = 0) uniform image2D image;

layout (set = 0, binding = 1) uniform TimeBuffer {
    float time;
} time;

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);
    if (texelCoord.x < size.x && texelCoord.y < size.y) {
        vec4 colour = vec4(0.0, 0.0, 0.0, 1.0);
        if (gl_LocalInvocationID.x != 0 && gl_LocalInvocationID.y != 0) {
            colour.x = float(texelCoord.x) / size.x;
            colour.y = float(texelCoord.y) / size.y;
            colour.xy *= sin(time.time * 0.5f);
        }
        imageStore(image, texelCoord, colour);
    }
}